# Generated by Django 5.2 for Nova messaging V5.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_user_last_seen_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="body",
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name="message",
            name="image",
            field=models.ImageField(blank=True, upload_to="messages/%Y/%m/"),
        ),
        migrations.AddField(
            model_name="message",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies",
                to="accounts.message",
            ),
        ),
        migrations.CreateModel(
            name="MessageReaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("emoji", models.CharField(max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("message", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="reactions", to="accounts.message")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="message_reactions", to="accounts.user")),
            ],
            options={
                "ordering": ("created_at", "id"),
                "indexes": [models.Index(fields=["message", "created_at"], name="msg_reaction_created_idx")],
                "constraints": [models.UniqueConstraint(fields=("message", "user"), name="unique_message_user_reaction")],
            },
        ),
    ]
