# Generated by Django 5.2 for Nova V2 closeout.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_group_conversations"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupConversationProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(blank=True, upload_to="groups/%Y/%m/"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "conversation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_profile",
                        to="accounts.conversation",
                    ),
                ),
            ],
        ),
    ]
