# Generated by Django 5.2.17 on 2026-08-24 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_approved_visual_capabilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomprofile',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomprofile',
            name='topics',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='AuthSessionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=64, unique=True)),
                ('device_name', models.CharField(blank=True, max_length=120)),
                ('platform', models.CharField(blank=True, max_length=24)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-last_seen_at', '-id'),
                'indexes': [models.Index(fields=['user', 'is_active', '-last_seen_at'], name='auth_session_user_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='MemoryDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('recap', 'Recap'), ('film', 'Film')], default='recap', max_length=8)),
                ('title', models.CharField(max_length=120)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('media', models.FileField(blank=True, upload_to='memories/drafts/%Y/%m/')),
                ('media_type', models.CharField(blank=True, max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at', '-id'),
                'indexes': [models.Index(fields=['user', '-updated_at'], name='memory_draft_user_updated_idx')],
            },
        ),
        migrations.CreateModel(
            name='PulseReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pulse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='accounts.pulse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pulse_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'constraints': [models.UniqueConstraint(fields=('pulse', 'user'), name='unique_pulse_reaction')],
            },
        ),
        migrations.CreateModel(
            name='PulseView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_viewed_at', models.DateTimeField(auto_now_add=True)),
                ('last_viewed_at', models.DateTimeField(auto_now=True)),
                ('pulse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='accounts.pulse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pulse_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-last_viewed_at', '-id'),
                'constraints': [models.UniqueConstraint(fields=('pulse', 'user'), name='unique_pulse_view')],
            },
        ),
        migrations.CreateModel(
            name='RoomFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='accounts.roomprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'constraints': [models.UniqueConstraint(fields=('user', 'room'), name='unique_room_follow')],
            },
        ),
    ]
